name: Go Check
description: Parse go/analysis reports and anotate diagnostics on the GitHub
inputs:
  go-vet-json:
    description: JSON files separated comma which go/analysis checkers reported
    default: diagnostics.json
  level:
    description: Which level to annotate, `warning` or `error`
    default: warning
  exit-code:
    description: Exit code when any diagnostics found
    default: 0
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -level
    - ${{ inputs.level }}
    - -exit-code
    - ${{ inputs.exit-code }}
    - ${{ inputs.go-vet-json }}

