name: Go Check
description: Parse go/analysis reports and anotate diagnostics on the GitHub
inputs:
  go-vet-json:
    description: A JSON file that a go/analysis (e.g. `go vet -json`) reported
    default: diagnostics.json
  level:
    description: Which level to annotate, `warning` or `error`
    default: warning
  exit-code:
    description: Exit code when any diagnostics found
    default: 0
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --level
    - ${{ inputs.level }}
    - --exit-code
    - ${{ inputs.exit-code }}
    - ${{ inputs.go-vet-json }}

