on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.14'
      - run: which go
      - run: go run -tags lint ./.github/workflows/check.go -json ./... > diagnostics.json
      - uses: ./annotate
