name: Deploy Docker Image

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/go-check

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set latest tag env
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      run: |
        echo "::set-env name=PKG_TAG::${DOCKER_BASE_NAME}:latest"

    - name: Set version tag env
    #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        echo "name=PKG_TAG::${DOCKER_BASE_NAME}:${GITHUB_REF#/refs/tags}"

    - name: Build base image
      run: |
        docker build . -t "${PKG_TAG}"

    - name: Login to registries
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Packages
      if: github.event_name != 'pull_request'
      run: docker push "${PKG_TAG}"
